import type { ThemeDefinition } from '@deepseek-ai/dsh-client-ui-theme/client'
import { ASUKA_COLORS as c } from './colors.js'

export const asukaDarkTheme: ThemeDefinition = {
  id: 'asuka-school-dark',
  colorScheme: 'dark',
  tokens: {
    '--dsw-alias-bg-base': c.nightNavy,
    '--dsw-alias-bg-layer-1': c.panelNavy,
    '--dsw-alias-bg-layer-2': '#26323E',
    '--dsw-alias-bg-layer-3': '#2C3946',
    '--dsw-alias-bg-overlay': '#26313C',
    '--dsw-alias-bg-mask-1': 'rgba(23, 28, 36, 0.82)',
    '--dsw-alias-bg-mask-2': 'rgba(23, 28, 36, 0.66)',
    '--dsw-alias-bg-mask-3': 'rgba(23, 28, 36, 0.48)',
    '--dsw-alias-border-l1': '#344452',
    '--dsw-alias-border-l2': '#4A5E6E',
    '--dsw-alias-border-l3': '#617A8D',
    '--dsw-alias-border-l4': c.tokyoSky,
    '--dsw-alias-brand-primary': '#E35A64',
    '--dsw-alias-brand-primary-invert': '#171C24',
    '--dsw-alias-brand-text': '#FF9A8D',
    '--dsw-alias-brand-primary-new-colorprimary-new-color': c.hairOrange,
    '--dsw-alias-label-primary': '#F4F0E9',
    '--dsw-alias-label-primary-bluish': c.hairOrangeHover,
    '--dsw-alias-label-secondary': '#C5D2D8',
    '--dsw-alias-label-tertiary': '#9DADB7',
    '--dsw-alias-label-caption': '#AAB9C0',
    '--dsw-alias-label-dimmed': '#73838D',
    '--dsw-alias-label-primary-inverted': '#171C24',
    '--dsw-alias-button-primary-fill': '#E35A64',
    '--dsw-alias-button-primary-hover': '#F06E73',
    '--dsw-alias-button-primary-dimmed': '#77424C',
    '--dsw-alias-button-info-fill': c.hairOrange,
    '--dsw-alias-button-info-hover': c.hairOrangeHover,
    '--dsw-alias-button-elevated-fill': '#2A3744',
    '--dsw-alias-button-floating-fill': '#2A3744',
    '--dsw-alias-button-floating-hover': '#354656',
    '--dsw-alias-button-ghost-active-fill': '#354A57',
    '--dsw-alias-button-ghost-active-border': c.tokyoSky,
    '--dsw-alias-interactive-bg-hover': '#2D3C48',
    '--dsw-alias-interactive-bg-active': '#3B4E5B',
    '--dsw-alias-interactive-bg-hover-accent': '#51333A',
    '--dsw-alias-state-error-primary': '#F17C82',
    '--dsw-alias-state-error-secondary': '#512E37',
    '--dsw-alias-state-success-primary': '#79B58D',
    '--dsw-alias-state-success-secondary': '#293F35',
    '--dsw-alias-state-success-tertiary': '#202F29',
    '--dsw-alias-state-business-primary': c.hairOrange,
    '--dsw-alias-state-business-tertiary': '#4D2D25',
    '--dsw-alias-state-warn-primary': '#E9AF58',
    '--dsw-alias-state-warn-secondary': '#4C3A20',
    '--dsw-alias-state-warn-tertiary': '#382D1D',
    '--dsw-alias-state-warn-label': '#F2C877',
    '--dsw-alias-markdown-code-block': '#10161D',
    '--dsw-alias-markdown-code-block-banner': '#1B2731',
    '--dsw-alias-markdown-inline-code': '#32323A',
    '--dsw-alias-scrollbar-bg-l1': '#24313C',
    '--dsw-alias-scrollbar-bg-l2': '#344452',
    '--dsw-alias-scrollbar-hover-l1': c.tokyoSky,
    '--dsw-alias-scrollbar-hover-l2': '#B7D7E7',
    '--dsw-specific-sidebar-fill': '#1C2731',
    '--dsw-specific-sidebar-nav-item-active': '#2E4351',
    '--dsw-specific-sidebar-nav-item-active-accent': '#F19863',
    '--dsw-specific-sidebar-nav-item-hover': '#273641',
    '--dsw-specific-bubble': '#25313C',
    '--dsw-specific-bubble-highlight': '#30343C',
    '--dsw-specific-input-major': '#202C36',
    '--dsw-static-deepseek-400': c.hairOrangeHover,
    '--dsw-static-deepseek-450': c.hairOrange,
    '--dsw-static-deepseek-500': c.hairOrangeAction,
    '--dsw-static-deepseek-600': c.hairOrangeDeep,
    '--shiki-background': '#10161D',
    '--shiki-foreground': '#E8EEF1',
    '--shiki-token-comment': '#7893A5',
    '--shiki-token-keyword': '#F09270',
    '--shiki-token-string': '#AED49A',
    '--shiki-token-function': '#F3C778',
    '--shiki-token-constant': '#E2A6C9',
    '--shiki-token-parameter': '#D7E1E5',
    '--shiki-token-punctuation': '#AEBEC7',
  },
}
