import type { ThemeDefinition } from '@deepseek-ai/dsh-client-ui-theme/client'
import { ASUKA_COLORS as c } from './colors.js'

const noonTokens = {
    '--asuka-code-block-sticky-mask': '#E8E9E4',
    '--dsw-alias-bg-base': 'rgba(232, 233, 228, 0.84)',
    '--dsw-alias-bg-layer-1': 'rgba(244, 243, 237, 0.92)',
    '--dsw-alias-bg-layer-2': 'rgba(236, 237, 232, 0.9)',
    '--dsw-alias-bg-layer-3': 'rgba(224, 225, 218, 0.92)',
    '--dsw-alias-bg-overlay': 'rgba(248, 247, 241, 0.94)',
    '--dsw-alias-bg-mask-1': 'rgba(224, 228, 224, 0.92)',
    '--dsw-alias-bg-mask-2': 'rgba(230, 233, 229, 0.7)',
    '--dsw-alias-bg-mask-3': 'rgba(238, 240, 235, 0.36)',
    '--dsw-alias-border-l1': '#D7D1C5',
    '--dsw-alias-border-l2': '#B9C7D0',
    '--dsw-alias-border-l3': '#98ADBA',
    '--dsw-alias-border-l4': c.schoolBlue,
    '--dsw-alias-brand-primary': c.ribbonRed,
    '--dsw-alias-brand-primary-invert': '#FFFFFF',
    '--dsw-alias-brand-text': c.ribbonRedDeep,
    '--dsw-alias-brand-primary-new-colorprimary-new-color': c.hairOrangeAction,
    '--dsw-alias-label-primary': c.ink,
    '--dsw-alias-label-primary-bluish': c.hairOrangeDeep,
    '--dsw-alias-label-secondary': '#354B59',
    '--dsw-alias-label-tertiary': '#465C69',
    '--dsw-alias-label-caption': '#405663',
    '--dsw-alias-label-dimmed': '#536874',
    '--dsw-alias-label-primary-inverted': '#FFFFFF',
    '--dsw-alias-button-primary-fill': c.ribbonRed,
    '--dsw-alias-button-primary-hover': c.ribbonRedDeep,
    '--dsw-alias-button-primary-dimmed': '#D98C91',
    '--dsw-alias-button-info-fill': c.hairOrangeAction,
    '--dsw-alias-button-info-hover': c.hairOrangeHover,
    '--dsw-alias-button-elevated-fill': '#FFFFFF',
    '--dsw-alias-button-floating-fill': '#FFFFFF',
    '--dsw-alias-button-floating-hover': '#F0E8DD',
    '--dsw-alias-button-ghost-active-fill': '#DCE6E8',
    '--dsw-alias-button-ghost-active-border': c.schoolBlue,
    '--dsw-alias-interactive-bg-hover': '#E7EEF0',
    '--dsw-alias-interactive-bg-active': '#D4E0E4',
    '--dsw-alias-interactive-bg-hover-accent': '#F3DEE0',
    '--dsw-alias-state-error-primary': c.error,
    '--dsw-alias-state-error-secondary': '#F6DFE1',
    '--dsw-alias-state-success-primary': c.success,
    '--dsw-alias-state-success-secondary': '#DEEEE3',
    '--dsw-alias-state-success-tertiary': '#F2F8F3',
    '--dsw-alias-state-business-primary': c.hairOrangeAction,
    '--dsw-alias-state-business-tertiary': '#F4D7C8',
    '--dsw-alias-state-warn-primary': c.warning,
    '--dsw-alias-state-warn-secondary': '#F8ECD8',
    '--dsw-alias-state-warn-tertiary': '#FFF8EB',
    '--dsw-alias-state-warn-label': '#754B13',
    '--dsw-alias-markdown-code-block': '#24313D',
    '--dsw-alias-markdown-code-block-banner': '#F3E8DB',
    '--dsw-alias-markdown-inline-code': '#EEE1D1',
    '--dsw-alias-scrollbar-bg-l1': '#E3DFD7',
    '--dsw-alias-scrollbar-bg-l2': '#D4D0C8',
    '--dsw-alias-scrollbar-hover-l1': c.schoolBlue,
    '--dsw-alias-scrollbar-hover-l2': c.schoolBlueDark,
    '--dsw-specific-sidebar-fill': 'rgba(220, 228, 228, 0.97)',
    '--dsw-specific-sidebar-nav-item-active': 'rgba(200, 216, 223, 0.98)',
    '--dsw-specific-sidebar-nav-item-active-accent': c.hairOrange,
    '--dsw-specific-sidebar-nav-item-hover': 'rgba(234, 240, 240, 0.98)',
    '--dsw-specific-bubble': 'rgba(255, 253, 248, 0.94)',
    '--dsw-specific-bubble-highlight': 'rgba(244, 234, 222, 0.94)',
    '--dsw-specific-input-major': 'rgba(255, 253, 248, 0.96)',
    '--dsw-static-deepseek-400': c.hairOrangeHover,
    '--dsw-static-deepseek-450': c.hairOrange,
    '--dsw-static-deepseek-500': c.hairOrangeAction,
    '--dsw-static-deepseek-600': c.hairOrangeDeep,
    '--shiki-background': '#24313D',
    '--shiki-foreground': '#E7EDF0',
    '--shiki-token-comment': '#91B9D2',
    '--shiki-token-keyword': '#F19863',
    '--shiki-token-string': '#B9D8A7',
    '--shiki-token-function': '#F3C988',
    '--shiki-token-constant': '#D9A5C7',
    '--shiki-token-parameter': '#DDE6EC',
    '--shiki-token-punctuation': '#B7C7D0',
}

/** Noon: quiet chalk-white rather than a bright blank canvas. */
export const asukaNoonTheme: ThemeDefinition = {
  id: 'asuka-school-noon',
  colorScheme: 'light',
  tokens: noonTokens,
}

/** Morning: muted orange paper that harmonizes with the commute scene. */
export const asukaMorningTheme: ThemeDefinition = {
  id: 'asuka-school-morning',
  colorScheme: 'light',
  tokens: {
    ...noonTokens,
    '--asuka-code-block-sticky-mask': '#DBC4B0',
    '--dsw-alias-bg-base': 'rgba(235, 215, 196, 0.82)',
    '--dsw-alias-bg-layer-1': 'rgba(248, 234, 220, 0.92)',
    '--dsw-alias-bg-layer-2': 'rgba(241, 220, 201, 0.9)',
    '--dsw-alias-bg-layer-3': 'rgba(229, 199, 176, 0.92)',
    '--dsw-alias-bg-overlay': 'rgba(251, 240, 229, 0.94)',
    '--dsw-alias-bg-mask-1': 'rgba(104, 59, 36, 0.9)',
    '--dsw-alias-bg-mask-2': 'rgba(188, 118, 74, 0.68)',
    '--dsw-alias-bg-mask-3': 'rgba(239, 197, 151, 0.34)',
    '--dsw-alias-label-primary-bluish': c.hairOrangeDeep,
    '--dsw-specific-sidebar-fill': 'rgba(235, 222, 207, 0.97)',
    '--dsw-specific-sidebar-nav-item-active': 'rgba(224, 199, 180, 0.98)',
    '--dsw-specific-sidebar-nav-item-hover': 'rgba(246, 232, 218, 0.98)',
    '--dsw-specific-bubble': 'rgba(255, 249, 242, 0.94)',
    '--dsw-specific-bubble-highlight': 'rgba(246, 226, 208, 0.94)',
    '--dsw-specific-input-major': 'rgba(255, 249, 242, 0.96)',
    '--dsw-alias-markdown-code-block': '#3D302C',
    '--dsw-alias-markdown-code-block-banner': '#F0D8C2',
  },
}

/** Backwards-compatible daytime export for consumers that do not select a period. */
export const asukaLightTheme = asukaNoonTheme
