import type { ThemeDefinition } from '@deepseek-ai/dsh-client-ui-theme/client'
import { ASUKA_COLORS as c } from './colors.js'

export const asukaLightTheme: ThemeDefinition = {
  id: 'asuka-school-light',
  colorScheme: 'light',
  tokens: {
    '--dsw-alias-bg-base': c.warmCream,
    '--dsw-alias-bg-layer-1': c.warmPaper,
    '--dsw-alias-bg-layer-2': '#F8F4EB',
    '--dsw-alias-bg-layer-3': '#EFE8DB',
    '--dsw-alias-bg-overlay': '#FFFDF8',
    '--dsw-alias-bg-mask-1': 'rgba(244, 240, 233, 0.76)',
    '--dsw-alias-bg-mask-2': 'rgba(244, 240, 233, 0.64)',
    '--dsw-alias-bg-mask-3': 'rgba(244, 240, 233, 0.48)',
    '--dsw-alias-border-l1': '#D7D1C5',
    '--dsw-alias-border-l2': '#B9C7D0',
    '--dsw-alias-border-l3': '#98ADBA',
    '--dsw-alias-border-l4': c.schoolBlue,
    '--dsw-alias-brand-primary': c.ribbonRed,
    '--dsw-alias-brand-primary-invert': '#FFFFFF',
    '--dsw-alias-brand-text': c.ribbonRedDeep,
    '--dsw-alias-label-primary': c.ink,
    '--dsw-alias-label-secondary': '#4C5F6C',
    '--dsw-alias-label-tertiary': '#71818B',
    '--dsw-alias-label-caption': '#697984',
    '--dsw-alias-label-dimmed': '#87949B',
    '--dsw-alias-label-primary-inverted': '#FFFFFF',
    '--dsw-alias-button-primary-fill': c.ribbonRed,
    '--dsw-alias-button-primary-hover': c.ribbonRedDeep,
    '--dsw-alias-button-primary-dimmed': '#D98C91',
    '--dsw-alias-button-elevated-fill': '#FFFFFF',
    '--dsw-alias-button-floating-fill': '#FFFFFF',
    '--dsw-alias-button-floating-hover': '#F0E8DD',
    '--dsw-alias-button-ghost-active-fill': '#DCE6E8',
    '--dsw-alias-button-ghost-active-border': c.schoolBlue,
    '--dsw-alias-interactive-bg-hover': '#E7EEF0',
    '--dsw-alias-interactive-bg-active': '#D4E0E4',
    '--dsw-alias-interactive-bg-hover-accent': '#F3DEE0',
    '--dsw-alias-state-error-primary': c.error,
    '--dsw-alias-state-error-secondary': '#F6DFE1',
    '--dsw-alias-state-success-primary': c.success,
    '--dsw-alias-state-success-secondary': '#DEEEE3',
    '--dsw-alias-state-success-tertiary': '#F2F8F3',
    '--dsw-alias-state-warn-primary': c.warning,
    '--dsw-alias-state-warn-secondary': '#F8ECD8',
    '--dsw-alias-state-warn-tertiary': '#FFF8EB',
    '--dsw-alias-state-warn-label': '#754B13',
    '--dsw-alias-markdown-code-block': '#24313D',
    '--dsw-alias-markdown-code-block-banner': '#30485D',
    '--dsw-alias-markdown-inline-code': '#EEE1D1',
    '--dsw-alias-scrollbar-bg-l1': '#E3DFD7',
    '--dsw-alias-scrollbar-bg-l2': '#D4D0C8',
    '--dsw-alias-scrollbar-hover-l1': c.schoolBlue,
    '--dsw-alias-scrollbar-hover-l2': c.schoolBlueDark,
    '--dsw-specific-sidebar-fill': '#DCE6E8',
    '--dsw-specific-sidebar-nav-item-active': '#C8D8DF',
    '--dsw-specific-sidebar-nav-item-active-accent': c.hairOrange,
    '--dsw-specific-sidebar-nav-item-hover': '#EAF0F0',
    '--dsw-specific-bubble': '#FFFDF8',
    '--dsw-specific-bubble-highlight': '#F4EADE',
    '--dsw-specific-input-major': '#FFFDF8',
    '--shiki-background': '#24313D',
    '--shiki-foreground': '#E7EDF0',
    '--shiki-token-comment': '#91B9D2',
    '--shiki-token-keyword': '#F19863',
    '--shiki-token-string': '#B9D8A7',
    '--shiki-token-function': '#F3C988',
    '--shiki-token-constant': '#D9A5C7',
    '--shiki-token-parameter': '#DDE6EC',
    '--shiki-token-punctuation': '#B7C7D0',
  },
}
